### ISSUE TITLE
Migration slow

### ISSUE THREAD

**Issue by araneta** [ngs-doo/dsl-compiler-client#82]
it took so much time maybe around 5 minutes to do migration process. i have 60 aggregate roots and 40 more snowflakes. do you know how to speed up this process?
thanks

**Comment by zapov** [comment]
It's possible that migration takes a while to run the analysis on larger projects.

Are you using Linux with Mono or Windows?
Mono is quite much slower (although it did improve with recent versions).
Maybe you can update to latest Mono?

It's an ongoing effort to optimize migrations so this will improve over time.
If you are just adding stuff... it might be much faster to just make a clean sql migration instead of performing a diff.

**Comment by zapov** [comment]
btw. I've uploaded a new version of the compiler with some performance improvements for the migration

Please try it out and let me know how long it takes now. Also, let me know which OS you use.

**Comment by araneta** [comment]
i'm using linux mint with mono
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 21 12:08:40 UTC 2016)
Could you give me the url of the new compiler? and how to clean sql migration?
Thanks

**Comment by zapov** [comment]
Latest compiler is downloaded from: https://tools.dsl-platform.com

I saw major performance improvements on Techempower with new Mono versions, so I would definitely try out the latest [Mono 5.2](http://www.mono-project.com/download/)

Thats mostly a hack but you can do it by truncating -DSL-.database_migration table

But I would rather you report such slowdowns and I fix them instead :)

**Comment by araneta** [comment]
should i also update dsl-clc.jar ? if yes where is the url of this file
Thanks

**Comment by zapov** [comment]
You probably don't need to. But if you want to it's on the releases page for this repository: https://github.com/ngs-doo/dsl-compiler-client/releases

**Comment by araneta** [comment]
great its faster now after updated the mono runtime
Thans
